### PR TITLE
95 implement schema validation

### LINKED ISSUE #95: implement schema validation
Schema validation landed on tdp-lib (https://github.com/TOSIT-IO/tdp-lib/pull/290), tdp-server should use this to be able to:

- Return the schema
- Validate input

### PR DESCRIPTION
**Pull request by gboutry**
#### Which issue(s) this PR fixes

Fixes #95 

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by PaulFarault — APPROVED** [review]

**Review by rpignolet — APPROVED** [review]

**Comment by PaulFarault** [comment]
It seems to work well.

However, why did you choose to parametrize the endpoint for each `serviceId`? As we can GET the whole list of services and components variables from the `/api/v1/services` endpoint, we could expect to get the whole schema too.

**Comment by gboutry** [comment]
Because it makes sense to get a schema for a specific service,

I can add a `/api/v1/service/schema` endpoint to get all the schemas, if it's better for you ?

**Comment by PaulFarault** [comment]
That could be useful.

Though, if we can fetch both the whole schema and schema / service, wouldn't it make sense to fetch it at the component level too?

**Comment by gboutry** [comment]
After some discussion with @PaulFarault we came to the conclusion that having a different basepath for schemas was more appropriate. Force push is reflecting this change.

Now, 2 endpoinst, 1 to get all schemas, 1 to get specific service schema.


> Though, if we can fetch both the whole schema and schema / service, wouldn't it make sense to fetch it at the component level too?

This does not make sense in the sense of how we defined schemas, but I agree that it looked weird before I separated the endpoints. I hope its clearer now.

**Review by PaulFarault — APPROVED** [review]
LGTM

**Pull request merged**
